# Generated by Django 3.2.20 on 2023-09-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/thumbnail.jpg', upload_to='blog/'),
        ),
    ]
