# Generated by Django 3.2.20 on 2023-09-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozayede', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطبین'},
        ),
    ]
